### ISSUE TITLE
Sound in atari emulators by ZX81

### ISSUE THREAD

**Issue by qbertaddict** [mthuurne/opendingux-kernel#3]
The sound in the atari emulators created by ZX81 is too high pitched.

**Comment by mthuurne** [comment]
Which emulators and their versions did you test exactly?

One thing to investigate is what frequency the emulator asked SDL for. We don't use the frequency scaler plugin for ALSA, so only frequencies that the hardware supports are available, but the hardware does provide the most common frequencies including 44.1kHz and 48kHz.

**Comment by qbertaddict** [comment]
## I tested the following emulators:

dingux-2600-v1.1.0-bin  
dingux-7800-v1.1.0-bin  
dingux-atari-v1.1.0-bin

Stella also has the same issues as Dingux-2600 but both are made using the same source.

These are the latest versions of these emulators

**Comment by mthuurne** [comment]
Ayla says the binaries of these emulators were statically linked against SDL, using OSS as the sound back-end. Since this report was filed, we have turned off the OSS compatibility drivers, so these emulators had to be recompiled and linked dynamically against SDL. Ayla has done so and the new versions play sound fine through SDL with the ALSA back-end.
